Update 1.0 Official release
frc4911/2024-Cresendo-Scouting-App pull request #9
Opened 2024-02-13 03:37 UTC by ipstolen

May add battle pass soon. Stay tuned for updates! Follow @ipstolen on insta for more updates. Jonathan Chu on LinkedIn.

2024-02-13 03:41 UTC, SuperCoderTrek approved these changes
Yes

2024-02-13 03:41 UTC, SuperCoderTrek approved these changes

2024-02-13 03:42 UTC, SuperCoderTrek approved these changes

2024-02-13 03:44 UTC, SuperCoderTrek approved these changes
I approve Github, let it go through

2024-02-13 04:29 UTC, Krylez requested changes
Delete the 3 extra files, but everything else looks good

2024-02-13 04:29 UTC, Krylez commented on ;
Can you delete this file?

2024-02-13 04:29 UTC, Krylez commented on coutingapp;
Delete this bad boy too

2024-02-13 04:29 UTC, Krylez commented on t
Also this one

2024-02-13 05:06 UTC, Krylez approved these changes

2024-02-14 02:16 UTC, deaves4911 commented on app/src/main/java/com/example/a2024frcscoutingapp/FileNameDialogFragment.java
> +        eventNames.add("potland");
should this be portland?

2024-02-14 02:16 UTC, deaves4911 commented on app/src/main/java/com/example/a2024frcscoutingapp/FileNameDialogFragment.java
> +                        String fileName = "2024 Cresendo " + (String) eventNameDropdown.getSelectedItem() + "_" + (String) tabletIdDropdown.getSelectedItem() + ".csv";
Did we want a space here after '2024 Cresendo'? It's usually best to use '_' instead of ' ' in file names. Also, should we call it 'Crescendo'?

2024-02-14 02:16 UTC, deaves4911 commented on app/src/main/java/com/example/a2024frcscoutingapp/MainActivity.java
> +            zAutoTarmac = (zAutoTarmac + 1)% climbDisplayText.length;
Using the length here is much better. Nice!

2024-02-14 02:24 UTC, ipstolen commented on app/src/main/java/com/example/a2024frcscoutingapp/FileNameDialogFragment.java
> +                        String fileName = "2024 Cresendo " + (String) eventNameDropdown.getSelectedItem() + "_" + (String) tabletIdDropdown.getSelectedItem() + ".csv";
You are right

2024-02-14 16:40 UTC, merged